Update patch set 5
Patch Set 5:

this broke Ace.

prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/../lib/gcc/arm-eabi/4.4.3/../../../../arm-eabi/bin/ld: out/target/product/ace/obj/SHARED_LIBRARIES/libaudio_intermediates/AudioHardware.o: in function android::updateDeviceInfo(unsigned int, unsigned int, unsigned int, unsigned int):hardware/msm7k/libaudio-msm7x30/AudioHardware.cpp:423: error: undefined reference to 'msm_device_mute'
collect2: ld returned 1 exit status

Patch-set: 5